// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @dev Minimal Coordinator interface (already defined in your system).
interface ICoordinator {
    function notifyProof(uint256 requestId, bytes32 proofHash) external;
    function notifyError(uint256 requestId, string calldata reason) external;
}

/// @dev Minimal Verifier smart contract interface.
/// @notice Can be implemented as a mock (always returns true)
///         or as a real verifier generated by snarkJS / another ZK system.
interface IVerifier {
    function verify(bytes calldata proof, bytes32 infoHash) external view returns (bool);
}

/// @title ProofManager for zk-oracle prototype
/// @notice Manages proof storage and coordinates with Verifier and Coordinator.
contract ProofManager {

    /// @notice Stored proof state.
    struct ProofRecord {
        bool exists;        // true if a proof is registered for this infoHash
        bytes32 infoHash;   // logical identifier (e.g. hash of compliance parameters)
        bytes32 proofHash;  // proof hash (e.g. keccak256(proof))
        bool isAggregate;   // true if proof is an aggregation of multiple proofs
        uint64 timestamp;   // storage timestamp (for experimental analysis)
    }

    /// @notice Contract admin (usually the deployer).
    address public admin;

    /// @notice On-chain Coordinator address.
    address public coordinator;

    /// @notice Off-chain oracle address authorized to submit proofs.
    address public oracle;

    /// @notice Verifier smart contract address (optional).
    address public verifier;

    /// @dev Mapping infoHash -> proof
    mapping(bytes32 => ProofRecord) private proofs;

    /// @notice Emitted when a proof is stored or updated.
    event ProofStored(bytes32 indexed infoHash, bytes32 proofHash, bool isAggregate);

    /// @notice Emitted when external contract references are updated.
    event CoordinatorSet(address coordinator);
    event OracleSet(address oracle);
    event VerifierSet(address verifier);

    modifier onlyAdmin() {
        require(msg.sender == admin, "ProofManager: not admin");
        _;
    }

    modifier onlyOracle() {
        require(msg.sender == oracle, "ProofManager: not oracle");
        _;
    }

    constructor(address _admin) {
        require(_admin != address(0), "ProofManager: zero admin");
        admin = _admin;
    }

    // ============================================================
    //  CONFIGURATION (to do in deployment script)
    // ============================================================

    /// @notice Sets Coordinator address.
    /// @dev Typically called by admin after Coordinator deployment.
    function setCoordinator(address _coordinator) external onlyAdmin {
        require(_coordinator != address(0), "ProofManager: zero coordinator");
        coordinator = _coordinator;
        emit CoordinatorSet(_coordinator);
    }

    /// @notice Sets oracle address (off-chain agent).
    function setOracle(address _oracle) external onlyAdmin {
        require(_oracle != address(0), "ProofManager: zero oracle");
        oracle = _oracle;
        emit OracleSet(_oracle);
    }

    /// @notice Sets Verifier smart contract address.
    /// @dev If unset (address(0)), on-chain verification is skipped.
    function setVerifier(address _verifier) external onlyAdmin {
        verifier = _verifier;
        emit VerifierSet(_verifier);
    }

    // ============================================================
    //  API used by Coordinator (via interface declared in Coordinator.sol)
    // ============================================================

    /// @notice Returns whether a proof already exists for a given infoHash,
    ///         used synchronously by Coordinator when a new request arrives.
    /// @return exists true if we have a proof, false otherwise
    /// @return proofHash proof hash (if exists == true)
    function getProofIfExists(bytes32 infoHash)
        external
        view
        returns (bool exists, bytes32 proofHash)
    {
        ProofRecord storage rec = proofs[infoHash];
        return (rec.exists, rec.proofHash);
    }

    // ============================================================
    //  API used by oracle (off-chain) for a specific request
    // ============================================================

    /// @notice Submits proof for a specific request,
    ///         optionally verifying through Verifier and notifying Coordinator.
    ///
    /// @param requestId request ID (emitted by Coordinator in VerificationRequested)
    /// @param infoHash logical verification identifier (must match Coordinator value)
    /// @param proof ZK proof bytes (or other proprietary format)
    /// @param isAggregate true if proof represents an aggregation of multiple proofs
    function submitProofForRequest(
        uint256 requestId,
        bytes32 infoHash,
        bytes calldata proof,
        bool isAggregate
    ) external onlyOracle {
        require(coordinator != address(0), "ProofManager: coordinator not set");

        // 1) If Verifier is configured, verify proof on-chain
        if (verifier != address(0)) {
            bool ok = IVerifier(verifier).verify(proof, infoHash);
            if (!ok) {
                ICoordinator(coordinator).notifyError(requestId, "Verification failed");
                return;
            }
        }

        // 2) If proof already exists for this infoHash, reuse it.
        ProofRecord storage rec = proofs[infoHash];
        bytes32 proofHashComputed;

        if (rec.exists) {
            // reuse existing proofHash
            proofHashComputed = rec.proofHash;
        } else {
            // first insertion for this infoHash
            proofHashComputed = keccak256(proof);

            rec.exists = true;
            rec.infoHash = infoHash;
            rec.proofHash = proofHashComputed;
            rec.isAggregate = isAggregate;
            rec.timestamp = uint64(block.timestamp);

            emit ProofStored(infoHash, proofHashComputed, isAggregate);
        }

        // 3) Notify Coordinator that proof (new or existing) is available
        ICoordinator(coordinator).notifyProof(requestId, proofHashComputed);
    }

    // ============================================================
    //  Read API for experimental analysis / client
    // ============================================================

    /// @notice Returns full proof details for a given infoHash.
    function getProofRecord(bytes32 infoHash)
        external
        view
        returns (
            bool exists,
            bytes32 infoHashOut,
            bytes32 proofHash,
            bool isAggregate,
            uint64 timestamp
        )
    {
        ProofRecord storage rec = proofs[infoHash];
        return (rec.exists, rec.infoHash, rec.proofHash, rec.isAggregate, rec.timestamp);
    }
}
