import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";
import { configVariable } from "hardhat/config";

/**
 * Complete deployment module for zk-oracle prototype
 * 
 * Deployment order:
 * 1. FuelUseVerifier (Groth16 verifier generated by snarkJS)
 * 2. VerifierAdapter (API adaptation wrapper)
 * 3. ProofManager (proof management)
 * 4. Coordinator (request entry point)
 * 5. Contract reference configuration
 */
export default buildModule("ZkOracleDeployment", (m) => {
  // Configurable parameters
  const adminAddress = m.getParameter("adminAddress");
  const oracleAddress = m.getParameter("oracleAddress");

  // 1. Deploy FuelUseVerifier
  const fuelUseVerifier = m.contract("FuelUseVerifier", [], {
    id: "FuelUseVerifier",
  });

  // 2. Deploy VerifierAdapter with FuelUseVerifier reference
  const verifierAdapter = m.contract("VerifierAdapter", [fuelUseVerifier], {
    id: "VerifierAdapter",
  });

  // 3. Deploy ProofManager with admin address
  const proofManager = m.contract("ProofManager", [adminAddress], {
    id: "ProofManager",
  });

  // 4. Deploy Coordinator with ProofManager reference
  const coordinator = m.contract("Coordinator", [proofManager], {
    id: "Coordinator",
  });

  // 5. ProofManager configuration
  // Set Coordinator in ProofManager
  m.call(proofManager, "setCoordinator", [coordinator], {
    id: "ProofManager_setCoordinator",
  });

  // Set Oracle in ProofManager
  m.call(proofManager, "setOracle", [oracleAddress], {
    id: "ProofManager_setOracle",
  });

  // Set Verifier in ProofManager
  m.call(proofManager, "setVerifier", [verifierAdapter], {
    id: "ProofManager_setVerifier",
  });

  return {
    fuelUseVerifier,
    verifierAdapter,
    proofManager,
    coordinator,
  };
});
